const std = @import("std");
const netz = @import("netz");

test "public modules are reachable" {
    try std.testing.expectEqualStrings("258EAFA5-E914-47DA-95CA-C5AB0DC85B11", netz.websocket.handshake_guid);
    try std.testing.expectEqual(@as(usize, 64 * 1024), (netz.http1.runtime.Limits{}).max_head_bytes);
    try std.testing.expect(@hasDecl(netz.http1.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasDecl(netz.http1.runtime, "readResponseFromStreamBuffered"));
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.websocket.runtime.Limits{}).max_frame_bytes);
    try std.testing.expect(@hasDecl(netz.websocket.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasField(netz.websocket.runtime.Connection, "send_mutex"));
    try std.testing.expectEqual(@as(u8, 0x40), netz.quic.varint.prefixForLength(2));
    try std.testing.expect(netz.http1.Method.GET.safe());
    try std.testing.expectEqual(@as(u64, 9), netz.http2.FrameHeader.encoded_len);
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.http2.runtime.Limits{}).max_body_bytes);
    try std.testing.expect(@hasDecl(netz.http2.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasDecl(netz.http2, "PingPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "GoAwayPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "WindowUpdatePayload"));
    try std.testing.expect(@hasDecl(netz.http2.runtime, "FlowWindow"));
    try std.testing.expectEqual(@as(u64, 0x01), netz.http3.FrameType.headers);
    try std.testing.expectEqual(@as(usize, 65_535), (netz.http3.runtime.Limits{}).quic.max_datagram_size);
    try std.testing.expect(@hasDecl(netz.http3.runtime.Server, "receiveRequestsConcurrent"));
    try std.testing.expect(@hasDecl(netz.http3.runtime, "ProtectedClient"));
    try std.testing.expect(@hasDecl(netz.http3.runtime, "HandshakeClient"));
    try std.testing.expect(@hasDecl(netz.http3, "SettingsState"));
    try std.testing.expectEqual(@as(u8, 5), netz.mqtt.ProtocolVersion.v5.byte());
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.mqtt.runtime.Limits{}).max_packet_size);
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasField(netz.mqtt.runtime.Connection, "max_outgoing_inflight"));
    try std.testing.expectEqual(@as(usize, 65_535), (netz.quic.runtime.Limits{}).max_datagram_size);
    try std.testing.expectEqual(@as(usize, 16), netz.quic.protection.aes_128_key_len);
    try std.testing.expect(@hasDecl(netz.quic.crypto_stream, "Reassembler"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "sendInitialCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "writeClientHello"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "deriveHandshakeSecrets"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "deriveApplicationSecrets"));
    try std.testing.expect(@hasDecl(netz.quic.handshake, "connect"));
    try std.testing.expect(@hasDecl(netz.quic.handshake, "accept"));
    try std.testing.expect(@hasDecl(netz.quic.connection_id, "PeerPool"));
    try std.testing.expect(@hasDecl(netz.quic.stateless_reset, "matches"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "sendFrames"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "Connection"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "closeTransport"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space, "ReceivedPacketTracker"));
    try std.testing.expect(@hasDecl(netz.quic.stream_state, "RecvState"));
    try std.testing.expect(@hasDecl(netz.quic.flow_control, "SendFlow"));
    try std.testing.expect(@hasDecl(netz.quic.recovery, "Queue"));
    try std.testing.expect(@hasDecl(netz.quic.congestion, "Controller"));
    try std.testing.expect(@hasDecl(netz.quic.path_validation, "State"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "receiveManyConcurrent"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "receiveRoutedBytes"));
    try std.testing.expect(@hasDecl(netz.quic.connection_router, "Router"));
    try std.testing.expect(netz.webtransport.SessionId.init(0).isClientInitiatedBidirectional());
    try std.testing.expect(@hasDecl(netz.webtransport, "SessionState"));
    try std.testing.expectEqual(@as(usize, 65_535), (netz.webtransport.runtime.Limits{}).http3.quic.max_datagram_size);
    try std.testing.expect(@hasDecl(netz.webtransport.runtime, "ProtectedClientSession"));
    try std.testing.expect(@hasDecl(netz.webtransport.runtime, "HandshakeClientSession"));
    try std.testing.expect(@hasDecl(netz.webtransport.runtime.HandshakeClientSession, "receiveManyDatagrams"));
    try std.testing.expectEqual(@as(u32, 0x2112A442), netz.webrtc.stun.magic_cookie);
    try std.testing.expectEqual(@as(usize, 2048), (netz.webrtc.runtime.Limits{}).max_datagram_size);
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "RtpClient"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "Peer"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "DtlsDatagram"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.Peer, "receiveManyConcurrent"));
}
