const std = @import("std");
const netz = @import("netz");

test "public modules are reachable" {
    try std.testing.expectEqualStrings("258EAFA5-E914-47DA-95CA-C5AB0DC85B11", netz.websocket.handshake_guid);
    try std.testing.expectEqual(@as(usize, 64 * 1024), (netz.http1.runtime.Limits{}).max_head_bytes);
    try std.testing.expect(@hasDecl(netz.http1.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasDecl(netz.http1.runtime, "readResponseFromStreamBuffered"));
    try std.testing.expect(@hasDecl(netz.http1, "ResponseContext"));
    try std.testing.expect(@hasDecl(netz.http1, "parseResponseForRequest"));
    try std.testing.expect(@hasDecl(netz.http1.runtime, "readResponseFromStreamBufferedForRequest"));
    try std.testing.expect(@hasDecl(netz.http1.runtime, "readRequestFromStreamBuffered"));
    try std.testing.expect(@hasDecl(netz.http1.runtime, "readResponseFromStreamForRequest"));
    try std.testing.expect(@hasField(netz.http1.runtime.RequestOptions, "trailers"));
    try std.testing.expect(@hasField(netz.http1.runtime.ResponseOptions, "trailers"));
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.websocket.runtime.Limits{}).max_frame_bytes);
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.websocket.runtime.Limits{}).max_message_bytes);
    try std.testing.expect(@hasDecl(netz.websocket.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasField(netz.websocket.runtime.Connection, "send_mutex"));
    try std.testing.expect(@hasDecl(netz.websocket.runtime, "OwnedMessage"));
    try std.testing.expect(@hasDecl(netz.websocket.runtime.Connection, "receiveMessage"));
    try std.testing.expect(@hasDecl(netz.websocket.runtime.Connection, "sendFragmented"));
    try std.testing.expect(@hasField(netz.websocket.runtime.Connection, "close_sent"));
    try std.testing.expect(@hasField(netz.websocket.runtime.Connection, "close_received"));
    try std.testing.expect(@hasField(netz.websocket.runtime.Connection, "selected_protocol"));
    try std.testing.expect(@hasField(netz.websocket.runtime.AcceptOptions, "protocols"));
    try std.testing.expect(@hasField(netz.websocket.runtime.ConnectOptions, "protocols"));
    try std.testing.expectEqual(@as(u8, 0x40), netz.quic.varint.prefixForLength(2));
    try std.testing.expect(netz.http1.Method.GET.safe());
    try std.testing.expect(std.meta.stringToEnum(netz.http1.BodyFraming, "close_delimited") != null);
    try std.testing.expect(@hasDecl(netz.http1, "validateTrailers"));
    try std.testing.expect(@hasDecl(netz.http1, "validateHeader"));
    try std.testing.expectEqual(@as(usize, 16 * 1024), netz.http1.max_chunk_extension_bytes);
    try std.testing.expectEqual(@as(u64, 9), netz.http2.FrameHeader.encoded_len);
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.http2.runtime.Limits{}).max_body_bytes);
    try std.testing.expectEqual(@as(usize, 16 * 1024), (netz.http2.runtime.Limits{}).max_header_list_size);
    try std.testing.expect(@hasDecl(netz.http2.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasField(netz.http2.runtime.RequestOptions, "trailers"));
    try std.testing.expect(@hasField(netz.http2.runtime.ResponseOptions, "trailers"));
    try std.testing.expect(@hasField(netz.http2.runtime.OwnedRequest, "trailers"));
    try std.testing.expect(@hasField(netz.http2.runtime.OwnedResponse, "trailers"));
    try std.testing.expect(@hasDecl(netz.http2, "PingPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "GoAwayPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "ResetStreamPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "WindowUpdatePayload"));
    try std.testing.expect(@hasDecl(netz.http2, "PriorityPayload"));
    try std.testing.expect(@hasDecl(netz.http2, "PushPromisePayload"));
    try std.testing.expect(@hasDecl(netz.http2, "validateSetting"));
    try std.testing.expect(@hasDecl(netz.http2.runtime, "FlowWindow"));
    try std.testing.expect(@hasDecl(netz.http2.runtime.Connection, "sendResetStream"));
    try std.testing.expect(@hasDecl(netz.http2.runtime.Connection, "readResetStream"));
    const stream_reset_error: netz.http2.runtime.Error = error.StreamReset;
    try std.testing.expect(stream_reset_error == error.StreamReset);
    const goaway_error: netz.http2.runtime.Error = error.ConnectionGoAway;
    try std.testing.expect(goaway_error == error.ConnectionGoAway);
    try std.testing.expectEqual(@as(u64, 0x01), netz.http3.FrameType.headers);
    try std.testing.expectEqual(@as(usize, 65_535), (netz.http3.runtime.Limits{}).quic.max_datagram_size);
    try std.testing.expect(@hasDecl(netz.http3.runtime.Server, "receiveRequestsConcurrent"));
    try std.testing.expect(@hasDecl(netz.http3.runtime, "ProtectedClient"));
    try std.testing.expect(@hasDecl(netz.http3.runtime, "HandshakeClient"));
    try std.testing.expect(@hasDecl(netz.http3, "SettingsState"));
    try std.testing.expect(@hasDecl(netz.http3, "ControlState"));
    try std.testing.expect(@hasDecl(netz.http3, "writeSettingsFrame"));
    try std.testing.expect(@hasDecl(netz.http3, "writeControlStreamPrefix"));
    try std.testing.expect(@hasDecl(netz.http3, "writeMaxPushIdFrame"));
    try std.testing.expect(@hasDecl(netz.http3, "writeCancelPushFrame"));
    try std.testing.expect(@hasDecl(netz.http3, "writePushPromiseFrame"));
    try std.testing.expect(@hasDecl(netz.http3, "parsePushPromisePayload"));
    try std.testing.expect(@hasField(netz.http3.Request, "trailers"));
    try std.testing.expect(@hasField(netz.http3.Response, "trailers"));
    try std.testing.expect(@hasField(netz.http3.DecodedRequest, "trailers"));
    try std.testing.expect(@hasField(netz.http3.DecodedResponse, "body_storage"));
    try std.testing.expect(@hasField(netz.http3.runtime.ProtectedConfig, "local_settings"));
    try std.testing.expect(@hasField(netz.http3.runtime.ProtectedClient, "control"));
    try std.testing.expect(@hasField(netz.http3.runtime.HandshakeClient, "control"));
    try std.testing.expectEqual(@as(u8, 5), netz.mqtt.ProtocolVersion.v5.byte());
    try std.testing.expect(@hasDecl(netz.mqtt, "validTopicName"));
    try std.testing.expect(@hasDecl(netz.mqtt, "validTopicFilter"));
    try std.testing.expect(@hasDecl(netz.mqtt, "topicMatchesFilter"));
    try std.testing.expect(@hasDecl(netz.mqtt, "LastWill"));
    try std.testing.expect(@hasDecl(netz.mqtt, "ConnectPacketOptions"));
    try std.testing.expect(@hasDecl(netz.mqtt, "writeConnectPacket"));
    try std.testing.expect(@hasField(netz.mqtt.Connect, "will"));
    try std.testing.expect(@hasField(netz.mqtt.runtime.ConnectOptions, "username"));
    try std.testing.expect(@hasField(netz.mqtt.runtime.ConnectOptions, "password"));
    try std.testing.expectEqual(@as(usize, 16 * 1024 * 1024), (netz.mqtt.runtime.Limits{}).max_packet_size);
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Server, "serveConcurrent"));
    try std.testing.expect(@hasField(netz.mqtt.runtime.Connection, "max_outgoing_inflight"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readPubAck"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "writePubRec"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readPubRec"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "writePubRel"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readPubRel"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "writePubComp"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readPubComp"));
    try std.testing.expect(@hasDecl(netz.mqtt, "Unsubscribe"));
    try std.testing.expect(@hasDecl(netz.mqtt, "UnsubAck"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "unsubscribe"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readUnsubscribe"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "writeUnsubAck"));
    try std.testing.expect(@hasDecl(netz.mqtt, "Auth"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "writeAuth"));
    try std.testing.expect(@hasDecl(netz.mqtt.runtime.Connection, "readAuth"));
    try std.testing.expectEqual(@as(usize, 65_535), (netz.quic.runtime.Limits{}).max_datagram_size);
    try std.testing.expectEqual(@as(usize, 16), netz.quic.protection.aes_128_key_len);
    try std.testing.expect(@hasDecl(netz.quic.crypto_stream, "Reassembler"));
    try std.testing.expectEqual(@as(usize, 1200), netz.quic.initial_exchange.min_initial_udp_datagram_size);
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "sendInitialCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "sendCoalescedInitialHandshakeCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "receiveCoalescedInitialHandshakeCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "openCoalescedInitialHandshakeCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "openInitialCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.initial_exchange, "openHandshakeCrypto"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "writeClientHello"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "deriveHandshakeSecrets"));
    try std.testing.expect(@hasDecl(netz.quic.tls_client_hello, "deriveApplicationSecrets"));
    try std.testing.expect(@hasDecl(netz.quic.handshake, "connect"));
    try std.testing.expect(@hasDecl(netz.quic.handshake, "accept"));
    try std.testing.expect(@hasDecl(netz.quic, "TransportParameters"));
    try std.testing.expect(@hasDecl(netz.quic, "parseTransportParametersTyped"));
    try std.testing.expect(@hasDecl(netz.quic, "encodeTransportParameters"));
    try std.testing.expect(@hasDecl(netz.quic, "validateTransportParameters"));
    try std.testing.expect(@hasDecl(netz.quic, "practical_transport_parameters"));
    try std.testing.expect(@hasDecl(netz.quic, "FramePacketType"));
    try std.testing.expect(@hasDecl(netz.quic, "frameAllowedInPacketType"));
    try std.testing.expect(@hasDecl(netz.quic, "validateFrameForPacketType"));
    try std.testing.expect(@hasDecl(netz.quic, "VersionNegotiationPacket"));
    try std.testing.expectEqual(@as(u64, 1) << 32, netz.quic.max_idle_timeout_ms_cap);
    try std.testing.expect(@hasDecl(netz.quic, "writeVersionNegotiationPacket"));
    try std.testing.expect(@hasDecl(netz.quic, "parseVersionNegotiationPacket"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "versionNegotiationResponse"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "sendVersionNegotiationIfUnsupported"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "receiveBytesHandlingVersionNegotiation"));
    try std.testing.expect(@hasDecl(netz.quic, "RetryPacket"));
    try std.testing.expect(@hasDecl(netz.quic, "writeRetryPacket"));
    try std.testing.expect(@hasDecl(netz.quic, "verifyRetryIntegrityTag"));
    try std.testing.expect(@hasField(netz.quic.handshake.ClientOptions, "local_transport_parameters"));
    try std.testing.expect(@hasField(netz.quic.handshake.ServerOptions, "local_transport_parameters"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "local_endpoint"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "initial_send_max_stream_data_bidi_local"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "initial_send_max_streams_bidi"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "initial_receive_max_streams_uni"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "enable_spin_bit"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "active_connection_id_limit"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "local_max_idle_timeout_ms"));
    try std.testing.expect(@hasField(netz.quic.one_rtt.ConnectionConfig, "peer_max_idle_timeout_ms"));
    try std.testing.expect(@hasDecl(netz.quic.connection_id, "PeerPool"));
    try std.testing.expect(@hasDecl(netz.quic.connection_id.PeerPool, "addWithLimit"));
    try std.testing.expect(@hasDecl(netz.quic.stateless_reset, "matches"));
    try std.testing.expectEqual(netz.quic.varint.max_value, netz.quic.protection.max_packet_number);
    try std.testing.expect(@hasDecl(netz.quic.protection, "packetNumberLen"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "packetNumberLenForPayload"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "initial_salt_v2"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "deriveInitialSecretsForVersion"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "deriveAes128KeysForVersion"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "peekProtectedLongPacketInfo"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "ProtectedLongPacketInfo"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "ZeroRttPacketOptions"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "sealZeroRttPacket"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "openZeroRttPacket"));
    try std.testing.expect(@hasField(netz.quic.protection.ShortPacketOptions, "spin_bit"));
    try std.testing.expect(@hasField(netz.quic.protection.OpenedShortPacket, "spin_bit"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "nextAes128PacketProtectionKeys"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "nextAes128PacketProtectionKeysForVersion"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "Aes128KeyPhaseState"));
    try std.testing.expect(@hasDecl(netz.quic.protection, "openShortPacketWithKeyUpdate"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "sendFrames"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "sendZeroRttFrames"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "receiveZeroRtt"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "openZeroRttBytes"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "receiveWithKeyUpdate"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "openReceivedBytesWithKeyUpdate"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "Connection"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "closeTransport"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "sendWithEcn"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "retransmitPacketThresholdLoss"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "localOneRttKeyPhase"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "peerOneRttKeyPhase"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "initiateKeyUpdate"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "pendingOneRttKeyUpdateAckThreshold"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "resetStream"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "sendStopSending"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "streamResetReceived"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "streamStopped"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "sendHandshakeDone"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "sendNewToken"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "latestNewToken"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "handshakeConfirmed"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "nextSpinBit"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "resetSpinBit"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "effectiveIdleTimeoutMillis"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "idleTimeoutDeadlineMillis"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "checkIdleTimeout"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "closing"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "draining"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt.Connection, "checkCloseExpired"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "CloseState"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "StreamResetInfo"));
    try std.testing.expect(@hasDecl(netz.quic.one_rtt, "StopSendingInfo"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space, "ReceivedPacketTracker"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.ReceivedPacketTracker, "wouldRecordFresh"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.ReceivedPacketTracker, "recordFresh"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space, "EcnCodepoint"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space, "default_packet_threshold"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.SentPacketTracker, "largestAcknowledged"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.SentPacketTracker, "sentWithEcn"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.SentPacketTracker, "validateAckEcnCounters"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.SentPacketTracker, "validateAckCoversSentPackets"));
    try std.testing.expect(@hasDecl(netz.quic.packet_space.SentPacketTracker, "detectPacketThresholdLoss"));
    try std.testing.expect(@hasDecl(netz.quic.stream_state, "RecvState"));
    const stream_conflict_error: netz.quic.stream_state.Error = error.ConflictingStreamData;
    try std.testing.expect(stream_conflict_error == error.ConflictingStreamData);
    const crypto_conflict_error: netz.quic.crypto_stream.Error = error.ConflictingCryptoData;
    try std.testing.expect(crypto_conflict_error == error.ConflictingCryptoData);
    try std.testing.expect(@hasDecl(netz.quic.flow_control, "SendFlow"));
    try std.testing.expect(@hasDecl(netz.quic.recovery, "Queue"));
    try std.testing.expect(@hasDecl(netz.quic.recovery.Queue, "packetThresholdCandidate"));
    try std.testing.expect(@hasDecl(netz.quic.congestion, "Controller"));
    try std.testing.expect(@hasDecl(netz.quic.path_validation, "State"));
    try std.testing.expect(@hasDecl(netz.quic.path_validation.State, "pendingChallengeCount"));
    try std.testing.expect(@hasDecl(netz.quic.rtt, "Stats"));
    try std.testing.expectEqual(@as(u64, 100_000_000), netz.quic.rtt.default_initial_rtt_ns);
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "receiveManyConcurrent"));
    try std.testing.expect(@hasDecl(netz.quic.runtime.Endpoint, "receiveRoutedBytes"));
    try std.testing.expect(@hasDecl(netz.quic.connection_router, "Router"));
    try std.testing.expect(netz.webtransport.SessionId.init(0).isClientInitiatedBidirectional());
    try std.testing.expect(@hasDecl(netz.webtransport, "SessionState"));
    try std.testing.expectEqual(@as(usize, 65_535), (netz.webtransport.runtime.Limits{}).http3.quic.max_datagram_size);
    try std.testing.expect(@hasDecl(netz.webtransport.runtime, "ProtectedClientSession"));
    try std.testing.expect(@hasDecl(netz.webtransport.runtime, "HandshakeClientSession"));
    try std.testing.expect(@hasDecl(netz.webtransport.runtime.HandshakeClientSession, "receiveManyDatagrams"));
    try std.testing.expectEqual(@as(u32, 0x2112A442), netz.webrtc.stun.magic_cookie);
    try std.testing.expect(@hasDecl(netz.webrtc.stun, "writeIceBindingRequest"));
    try std.testing.expect(@hasDecl(netz.webrtc.stun, "validateMessageIntegrity"));
    try std.testing.expect(@hasDecl(netz.webrtc.stun, "validateFingerprint"));
    try std.testing.expect(@hasDecl(netz.webrtc.stun, "BindingRequestOptions"));
    try std.testing.expect(@hasDecl(netz.webrtc, "rtcp"));
    try std.testing.expect(@hasDecl(netz.webrtc.rtcp, "ReceiverReport"));
    try std.testing.expect(@hasDecl(netz.webrtc.rtcp, "PictureLossIndication"));
    try std.testing.expect(@hasDecl(netz.webrtc.rtcp, "TransportLayerNack"));
    try std.testing.expect(@hasDecl(netz.webrtc.sdp, "extractFingerprint"));
    try std.testing.expect(@hasDecl(netz.webrtc.sdp, "extractIceCredentials"));
    try std.testing.expect(@hasDecl(netz.webrtc.sdp, "Fingerprint"));
    try std.testing.expect(@hasDecl(netz.webrtc.sdp, "IceCredentials"));
    try std.testing.expect(@hasDecl(netz.webrtc.sctp, "DataChunk"));
    try std.testing.expect(@hasDecl(netz.webrtc.sctp, "writeDataPacket"));
    try std.testing.expect(@hasDecl(netz.webrtc.sctp, "parseDcepMessage"));
    try std.testing.expectEqual(@as(usize, 2048), (netz.webrtc.runtime.Limits{}).max_datagram_size);
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "RtpClient"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "Peer"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "DtlsDatagram"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime, "RtcpDatagram"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.Peer, "sendRtcpPacket"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.Peer, "receiveRtcpPacket"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.Peer, "iceBindingRequest"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.StunClient, "iceBindingRequest"));
    try std.testing.expect(@hasDecl(netz.webrtc.runtime.Peer, "receiveManyConcurrent"));
}
