[package]
name = "netz-hyper-http2-flow"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "netz-hyper-http2-interop-server"
path = "src/bin/interop_server.rs"

[dependencies]
bytes = "1.2"
futures-util = "0.3"
http-body-util = "0.1"
hyper = { path = "../../../../Work/hyper", features = ["client", "http2", "server"] }
pin-project-lite = "0.2"
tokio = { version = "1", features = ["io-util", "net", "rt", "sync"] }
